# Generated by Django 5.2.8 on 2025-11-07 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('edad', models.CharField(max_length=10)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('puntos_fidelidad', models.PositiveIntegerField(default=0)),
                ('avatar', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('numero_orden', models.PositiveIntegerField(unique=True)),
                ('cantidad_items', models.PositiveIntegerField()),
                ('tipo_orden', models.CharField(choices=[('Comida', 'Comida'), ('Bebida', 'Bebida'), ('Postre', 'Postre')], max_length=30)),
                ('metodo_pago', models.CharField(default='Efectivo', max_length=30)),
                ('completada', models.BooleanField(default=False)),
                ('mesa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('horas_trabajadas', models.PositiveIntegerField(help_text='Horas trabajadas')),
                ('puesto', models.CharField(max_length=10)),
                ('turno', models.CharField(max_length=50)),
                ('fecha_contratacion', models.DateField()),
                ('clientes', models.ManyToManyField(related_name='empleados', to='app_cafeteria.clientes')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='app_cafeteria.orden')),
            ],
        ),
    ]
